joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.75
    scale_linear_turbo:
      x: 2.2

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.75
    scale_angular_turbo:
      yaw: 1.5

    enable_button: 4
    enable_turbo_button: 5

    # "Deadman switch" for the teleop node
    # Either left or right bumper has to be held down to move
    require_enable_button: true
