<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
  <!-- File that contains details relating to the RPLidar we are going to be using -->
  <!-- RPLIDAR -->

  <joint name="laser_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="laser_frame"/>
    <origin xyz="${lidar_x_offset} ${lidar_y_offset} ${lidar_z_offset}" rpy="0 0 0"/>
  </joint>

  <!-- Laser frame follows some  -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.170" length="${lidar_height}" radius="${lidar_radius}">
      <origin xyz="0 0 ${lidar_height / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="laser_frame">
    <material>Gazebo/Red</material>

    <sensor name="laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>

      <!-- 10 times/sec -->
      <update_rate>10</update_rate>

      <!-- Params for the type "ray" -->
      <!-- Took these from the AIM8 datasheet -->
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            
            <!-- +-180 degrees (Radians) -->
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <!-- 0.15-12.0 per the datasheet -->
          <min>0.3</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>

      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frameName>laser_frame</frameName>
      </plugin>
    </sensor>
    
  </gazebo>

</robot>